### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by curtcorum** [ismrmrd/ge_to_ismrmrd#1]
Is there a preferred version of the orchestra-sdk?
Version 1.6.1 seems to have a different directory structure than the version originally used.
CMAKE fails to find various dependencies or thinks orchestra is not present depending on $SDKTOP.

**Comment by hansenms** [comment]
@roopchansinghv This one is for you.

**Comment by roopchansinghv** [comment]
The last version of Orchestra I verified the build of ge_to_ismrmrd with is Orchestra 1.3-24.  I recently updated to 1.6, but ran into the same issues you did, and have not had a chance to work through the new directory structure.

**Comment by roopchansinghv** [comment]
I've created a new branch of this converter (test_1.6) that compiles against the 1.6 version of the Orchestra SDK.  However, there is an issue on my platform with building ISMRMRD with the vendor's supplied static HDF5 libraries.  See here:

   https://github.com/ismrmrd/ismrmrd/issues/97

However, this issue might be particular to my setup.  Feel free to build ISMRMRD as prescribed here, then build ge_to_ismrmrd, and let us know if you can run the base test.

**Comment by roopchansinghv** [comment]
Removing the version of HDF5 supplied by the OS I use (openSUSE) and using the version that comes with Orchestra, along with the updated compiler flags, resolved this issue.  When converting the P-file supplied with this repository, the command ends with a "Segmentation fault" message.  However, a HDF5 file is generated, and when reconstructed, produces an image, and passes the basic test.
