### ISSUE TITLE
Orchestra SDK

### ISSUE THREAD

**Issue by tharagireesh** [ismrmrd/ge_to_ismrmrd#4]
Hello all,

I want to convert raw data from a GE scanner to ISMRMRD. But I don't have access to Orchestra SDK. Is there a way to convert GE data to ISMRMRD without using Orchestra SDK?

Thanks.

**Comment by hansenms** [comment]
It all depends on how you plan on reading the GE files. If you have code for reading them in say MATLAB, then you would probably you that to read the files and then use the MATLAB library for ISMRMRD. Similarly if you have C++ code for reading your files, then you would start there. 

How are you currently reading your GE files?

**Comment by HoenikkerPerez** [comment]
I can't compile. (I tried many orchestra distros). Cmake seems to find well the orchestra's libraries, but can't link them. I'm using Ubuntu 16, do you have any advice?

[comp_error.txt](https://github.com/ismrmrd/ge_to_ismrmrd/files/3106608/comp_error.txt)
