### ISSUE TITLE
Errors with building on Ubuntu 16

### ISSUE THREAD

**Issue by roopchansinghv** [ismrmrd/ge_to_ismrmrd#5]
I can't compile. (I tried many orchestra distros). Cmake seems to find well the orchestra's libraries, but can't link them. I'm using Ubuntu 16, do you have any advice?

[comp_error.txt](https://github.com/ismrmrd/ge_to_ismrmrd/files/3106608/comp_error.txt)

_Originally posted by @HoenikkerPerez in https://github.com/ismrmrd/ge_to_ismrmrd/issues/4#issuecomment-485699496_

**Comment by roopchansinghv** [comment]
We ran into similar looking compile error messages when we were trying to build the converter using the current Gadgetron container pulled from Docker Hub.  As far as we can **guess**, the issue seems to be with GE using a RedHat-based linux distribution to build its Orchestra environment.  The compiler versions there, and (pertinent to the errors you included above) the C++ ABIs used to build the system Boost are probably "too new" to use with Orchestra.

We developed a work-around for Ubuntu 18 (which is the container currently used for the default Gadgetron container you can pull from Docker Hub), in preparation for the ISMRM 2019 meeting.  Please see:

   https://github.com/NHLBI-MR/ISMRM2019_demo/tree/master/GE_converter_demo

Here, we had to re-build the basic ISMRMRD library itself, using both the Boost and HDF libraries supplied by Orchestra, then we could build the GE-to-ISMRMRD converter.

The best solution seems to be to create a basic container just to do the GE converter, with the compilers and ABIs compatible with Orchestra's build environment (openSUSE 42.3 works well for us - we haven't tested later), then you can track the newer Gadgetron and ISMRMRD releases in a separate machine / container.

Let us know if this helps or not.

Cheers!

**Comment by HoenikkerPerez** [comment]
Thanks for your help, I'll let you know as soon as possible if I can compile it.

**Comment by HoenikkerPerez** [comment]
I tried to compile with  the flag -D_GLIBCXX_USE_CXX11_ABI in order to face the ABI problem, without good results. I'm trying with the docker containers, but the documentation of the converter_demo refers to a prepared AWS virtual machine. 
Cheers

**Comment by roopchansinghv** [comment]
Are the errors the same as before, or are they new?  If they are different, could you also post that log please?

Also, would you be willing to give this container a try, and see if that works better to build as your build environment:

https://github.com/nih-fmrif/dockerImage4DevMR/tree/DV26.0_R01+Orch_1.6

This is the one we use most, and it's been relatively issue-free, building the converter.

**Comment by HoenikkerPerez** [comment]
I solved changing some stuff on makefiles and using another libboost version. Btw i'll try the container. Thanks a lot.

**Comment by roopchansinghv** [comment]
Would you be willing to share some details of the machine / container you are using here on this thread, and the changes to the CMakeLists.txt files you made, to get it to compile?  That information may prove useful for others.

Thanks!
